# Minimal Automattes Makefile
INSTDIR = $(HIH)
SOURCES =  ./src/MurmurHash3.cpp ./src/VEX_AutomattesHash.cpp 
OPTIMIZER = -O3
LIBDIRS = -L$(HIH)/dso -Wl,-rpath="./"
LIBS    = -lAutomattesHelper
DSONAME = VEX_AutomattesHash.so
# Include HDK Makefile.
include $(HT)/makefiles/Makefile.gnu